AXF/AXF/urls.py
from django.conf.urls import url
from django.contrib import admin

from App import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include),
    url(r'^$', views.home),
]

AXF/App/models.py
from django.db import models


class Main(models.Model):
    img = models.CharField(max_length=200)
    name = models.CharField(max_length=100)
    trackid = models.CharField(max_length=16)

    class Meta:
        abstract = True


class MainWheel(Main):

    class Meta:
        db_table = "axf_wheel"


class MainNav(Main):

    class Meta:
        db_table = "axf_nav"


class MainMustBuy(Main):

    class Meta:
        db_table = 'axf_mustbuy'


class MainShop(Main):

    class Meta:
        db_table = 'axf_shop'


"""
insert into axf_mainshow
(trackid,name,img,categoryid,brandname,img1,childcid1,productid1,longname1,price1,marketprice1,
img2,childcid2,productid2,longname2,price2,marketprice2,img3,childcid3,productid3,longname3,price3,marketprice3)
 values("21782","优选水果","http://img01.bqstatic.com//upload/activity/2017031018205492.jpg@90Q.jpg",
 "103532","爱鲜蜂","http://img01.bqstatic.com/upload/goods/201/701/1916/20170119164159_996462.jpg@200w_200h_90Q",
 "103533","118824","爱鲜蜂·特小凤西瓜1.5-2.5kg/粒","25.80","25.8","http://img01.bqstatic.com/upload/goods/201/611/1617/20161116173544_219028.jpg@200w_200h_90Q",
 "103534","116950","蜂觅·越南直采红心火龙果350-450g/盒","15.3","15.8","http://img01.bqstatic.com/upload/goods/201/701/1916/20170119164119_550363.jpg@200w_200h_90Q",
 "103533","118826","爱鲜蜂·海南千禧果400-450g/盒","9.9","13.8");


"""
class MainShow(Main):
    categoryid = models.CharField(max_length=16)
    brandname = models.CharField(max_length=100)
    img1 = models.CharField(max_length=200)
    childcid1 = models.CharField(max_length=16)
    productid1 = models.CharField(max_length=16)
    longname1 = models.CharField(max_length=100)
    price1 = models.FloatField(default=0)
    marketprice1 = models.FloatField(default=1)
    img2 = models.CharField(max_length=200)
    childcid2 = models.CharField(max_length=16)
    productid2 = models.CharField(max_length=16)
    longname2 = models.CharField(max_length=100)
    price2 = models.FloatField(default=0)
    marketprice2 = models.FloatField(default=1)
    img3 = models.CharField(max_length=200)
    childcid3 = models.CharField(max_length=16)
    productid3 = models.CharField(max_length=16)
    longname3 = models.CharField(max_length=100)
    price3 = models.FloatField(default=0)
    marketprice3 = models.FloatField(default=1)

    class Meta:
        db_table = "axf_mainshow"


"""
        (typeid,typename,childtypenames,typesort)
"""
class FoodType(models.Model):
    typeid = models.CharField(max_length=16)
    typename = models.CharField(max_length=100)
    childtypenames = models.CharField(max_length=200)
    typesort = models.IntegerField(default=1)

    class Meta:
        db_table = "axf_foodtypes"


"""
insert into axf_goods
(productid,productimg,productname,productlongname,isxf,pmdesc,specifics,price,marketprice,
categoryid,childcid,childcidname,dealerid,storenums,productnum) 
values("11951","http://img01.bqstatic.com/upload/goods/000/001/1951/0000011951_63930.jpg@200w_200h_90Q","",
"乐吧薯片鲜虾味50.0g",0,0,"50g",2.00,2.500000,103541,103543,"膨化食品","4858",200,4);
"""
class Goods(models.Model):
    productid = models.CharField(max_length=16)
    productimg = models.CharField(max_length=200)
    productname = models.CharField(max_length=100)
    productlongname = models.CharField(max_length=200)
    isxf = models.IntegerField(default=1)
    pmdesc = models.CharField(max_length=100)
    specifics = models.CharField(max_length=100)
    price = models.FloatField(default=0)
    marketprice = models.FloatField(default=1)
    categoryid = models.CharField(max_length=16)
    childcid = models.CharField(max_length=16)
    childcidname = models.CharField(max_length=100)
    dealerid = models.CharField(max_length=16)
    storenums = models.IntegerField(default=1)
    productnum = models.IntegerField(default=1)

    class Meta:
        db_table = "axf_goods"


class UserModel(models.Model):
    username = models.CharField(max_length=32, unique=True)
    password = models.CharField(max_length=256)
    email = models.CharField(max_length=64, unique=True)
    # False 代表女
    sex = models.BooleanField(default=False)
    icon = models.ImageField(upload_to='icons')
    is_delete = models.BooleanField(default=False)


class CartModel(models.Model):
    user = models.ForeignKey(UserModel)
    goods = models.ForeignKey(Goods)
    c_num = models.IntegerField(default=1)
    is_select= models.BooleanField(default=True)


class OrderModel(models.Model):
    user = models.ForeignKey(UserModel)
    o_num = models.CharField(max_length=64)
    # 0 代表已下单，但是未付款， 1 已付款未发货  2 已付款，已发货.....
    o_status = models.IntegerField(default=0)
    o_create = models.DateTimeField(auto_now=True)


class OrderGoodsModel(models.Model):
    goods = models.ForeignKey(Goods)
    order = models.ForeignKey(OrderModel)
    goods_num = models.IntegerField(default=1)

AXF/templates/order/order_info.html
{% extends 'base.html' %}
{% load static %}

{% block EXTJS %}
    <script type="text/javascript" src="{% static 'app/order/js/order.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="order_info" class="container">


    <h3>订单编号:{{ order_id }}</h3>

    <ul>

        {% for ordergoods in order.ordergoodsmodel_set.all %}

            <li>

                <img src="{{ ordergoods.goods.productimg }}">

                <span>{{ ordergoods.goods_num }}</span>
            </li>


        {% endfor %}


    </ul>

        <button id="alipay" class="btn btn-success btn-block" orderid="{{ order_id }}">Alipay</button>

    </div>


{% endblock %}

AXF/templates/order/order_list_payed.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待收货订单列表</h3>

    <ul>
        {% for order in orders %}
            <li>
                <a href="#">
                    <p>{{ order.id }}</p>
                    <p>{{ order.o_num }}</p>
                    {% for ordermodel in order.ordergoodsmodel_set.all %}
                        <li>
                            <img src="{{ ordermodel.goods.productimg }}" alt="">
                        </li>
                    {% endfor %}
                </a>
            </li>
        {% endfor %}


    </ul>


{% endblock %}

AXF/templates/order/order_list_wait_pay.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待付款订单列表</h3>

    <ul>
        {% for order in orders %}
            <li>
                <a href="{% url 'axf:order_info' order.id %}">
                    <p>{{ order.id }}</p>
                    <p>{{ order.o_num }}</p>
                    {% for ordermodel in order.ordergoodsmodel_set.all %}
                        <li>
                            <img src="{{ ordermodel.goods.productimg }}" alt="">
                        </li>
                    {% endfor %}
                </a>
            </li>
        {% endfor %}


    </ul>


{% endblock %}